### ISSUE TITLE
Add RestartPolicy to started containers

### ISSUE THREAD

**Issue by sebastianneubauer** [blue-yonder/postgraas_server#1]
Currently, if containers are stopped, they are not automatically restarted. This desired behaviour can be reached via RestartPolicy settings...

**Comment by jneuff** [comment]
The relevant docker configuration is https://docs.docker.com/engine/reference/run/#restart-policies-restart
"unless-stopped" seems to be a sane choice.

**Comment by jneuff** [comment]
Implemented in https://github.com/blue-yonder/postgraas_server/pull/4/commits/322e381b1ae70ec1863e4e383a8af3fc9c82866d
