### ISSUE TITLE
GET should return sensible hostname

### ISSUE THREAD

**Issue by byjott** [blue-yonder/postgraas_server#11]
The GET command currently returns 'not imlemented yet' as hostname.

Various solutions are possible:
- completely omit the 'hostname' key. After all, all postgres instances are created on the same server that runs the REST API webservice. Therefore, clients can just use the same address / server name to connect to the postgres instances as they use for the REST API calls.
- make the returned hostname configurable (e.g. in a new section `globals`). Could use `socket.getfqdn` as default.

**Comment by sebastianneubauer** [comment]
Sorry for the inacceptable long delay for an answer.
In the newest version, the "hostname" is configurable, so this should solve this sufficiently...depending on the backend, this is as good as it can get get with reasonable amount of effort. 
I will close the issue for now, but feel free to reopen it, if there is still something essential missing...
