### ISSUE TITLE
Postgraas server leaks database connections

### ISSUE THREAD

**Issue by StephanErb** [blue-yonder/postgraas_server#19]
It appears that:

* Postgraas does not properly close unused database connections
    * Example A: https://github.com/blue-yonder/postgraas_server/blob/master/postgraas_server/backends/postgres_cluster/postgres_cluster_driver.py#L19
    * Example B (error case not considered): https://github.com/blue-yonder/postgraas_server/blob/master/postgraas_server/prometheus_app.py#L30
    * Example C (via SQLAlchemy session): https://github.com/blue-yonder/postgraas_server/blob/4c848150d023de009af635a7eba9a40b22931aa1/postgraas_server/management_resources.py#L116
* Postgraas uses SQLAlchemy pools. In addition to the changes above it is probably worthwhile to switch to an explicit `NullPool`. We don't need the performance advantage that a pool offers.

**Comment by sebastianneubauer** [comment]
This issue is fixed by #27 right?
